mistral-7b-ift-v2.6:
  prompt_template: "mistral-7b-ift-v2.6/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "HuggingFaceH4/mistral-7b-ift"
    model_kwargs:
      torch_dtype: 'bfloat16'
      revision: v2.6
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Mistral 7B IFT v2.6"
  link: "https://huggingface.co/HuggingFaceH4/mistral-7b-ift"